r-lib/mirai

.github/workflows/check-standard.yaml, .github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, NEWS.md, R/daemon.R, R/daemons.R, R/dispatcher.R, man/daemon.Rd, man/daemons.Rd, man/saisei.Rd, tests/tests.R
=> Allow daemons to raise a signal upon autoexit

vignettes/shiny.Rmd
The way this was written, the daemons would be shut down at the end of a _session_, not when the app stops.
=> Move shiny::onStop in vignette

DESCRIPTION
The remotes or pak packages can't install the GH version of mirai since the remote for doesn't include the repo name: 
```
> pak::pak("shikokuchuo/mirai", ask = FALSE)
✔ Loading metadata database ... done                          
Error:                                                                     
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* shikokuchuo/mirai: Can't install dependency nanonext (>= 1.2.1.9002) 
```
This PR adds that to `remotes:`.
=> use GH url for remote

DESCRIPTION, NEWS.md, R/daemon.R, R/dispatcher.R, man/daemon.Rd, man/dispatcher.Rd, tests/tests.R
- Moves 'asyncdial' from `dispatcher()` to `daemon()`
- Reduces overloading of 'autoexit' argument
=> Allow more granular control of daemons

DESCRIPTION, NEWS.md, R/daemons.R, man/daemons.Rd, tests/tests.R
Adds argument 'force'.
Defaults to TRUE so no change in existing behaviour, although this was only brought in fairly recently in mirai 1.1.0.
The previous behaviour had the advantage of "being explicit", but introduced a behavioural dependency on past actions which could be confusing for interactive use.
Adding this setting improves behaviour for programmatic use, where the presumption is to set `force = FALSE`.
For #137, packages using `mirai` could then reliably use this without overriding any settings explicitly specified by users outside of their packages.
=> Allow control over whether to reset daemons settings

DESCRIPTION, NEWS.md, R/daemon.R
Fixes #166.
@wlandau this is my proposed fix. Please let me know if you can think of any corner cases - I can't think how this change would be problematic. Thanks!
=> Do not unload namespaces in package cleanup

DESCRIPTION, NEWS.md, R/daemon.R, R/daemons.R, R/dispatcher.R, man/daemon.Rd, man/status.Rd, tests/tests.R
Allows us to tell which daemons are online at any given time.
Useful when launches are lengthy and unpredictable e.g. queued on a cluster system or in cloud infrastructure.
@wlandau.
=> Implement Daemon IDs

NEWS.md, R/map.R, R/mirai.R, man/collect_mirai.Rd, man/everywhere.Rd, man/mirai.Rd, tests/tests.R
Removes NSE from `collect_mirai()` to allow easier programmatic use.
=> Add 'options' argument for collect_mirai()

R/map.R, man/mirai_map.Rd
In light of #192. Closes #192.
=> Update Multiple Map Docs and Examples

vignettes/promises.Rmd
From `&...>%`  -> `%..>%` in https://shikokuchuo.net/mirai/articles/promises.html
=> Fix typo in promises vignette

NEWS.md, R/mirai.R, man/call_mirai.Rd, man/collect_mirai.Rd
Makes `call_mirai()` user-interruptible.
- Negates the needs for a separate awkwardly-named `call_mirai_()`
This completes the transition to entirely user-interruptible functions across the package.
- Follows decision to make `[` method interruptible by default when it was introduced in mirai 1.1.0.
- `collect_mirai()` made interruptible in mirai 2.0.0.
Since nanonext 1.3.1, all interruptible waits are performed by a long-lived dedicated thread hence the overhead vs. a blocking call is miniscule. For truly critical applications, the equivalent blocking functions may be used directly from nanonext.
=> UI consistency wrt interruptibility

NEWS.md, R/mirai.R, tests/tests.R
Fixes #207.
The conversion of the environment to a list using `as.list.environment()` must specify `all.names = TRUE`.
=> mirai accepts an environment containing dot-variables

R/mirai.R, tests/tests.R
Special case `.Random.seed` when passing an environment to `...`
Really fixes #207.
=> Fix `mirai()` accepting an environment containing dot-variables

NEWS.md, R/daemons.R, R/mirai-package.R, tests/tests.R
Fixes #211.
Preserves explicit behaviour from #200 by issuing an immediate warning.
Otherwise retains behaviour prior to mirai 2.1.0 by revised settings (without a reset) having no effect.
=> Reverts `daemons()` error behaviour for revised settings

vignettes/mirai.Rmd, vignettes/mirai.Rmd.orig
- Clearer stipulations for `daemons()`:
+ Never use for `mirai_map()` or `purrr::map(.parallel = TRUE)`
+ May be appropriate for single dedicated daemons e.g. `logger::appender_async()`
- Removes non-essential sections.
=> Update 'using mirai in a package' section of vignette

NEWS.md, R/daemons.R, R/launchers.R, R/map.R, R/mirai-package.R, R/mirai.R, tests/tests.R
Try to preserve existing behaviour with the compute profile as the character string `"default"`. This is in the end no different to using a `current_profile()` getter function or some sentinel such as `NULL`.
Solution employed is to use one layer of indirection if the `.compute` argument is missing. Functions which set a temporary state, such as the `with()` method for `daemons()`, set what `"default"` actually directs to.
Lays the groundwork for an implementation of `with_daemons()` / `local_daemons()` or `with_profile()` / `local_profile()` - some further thought needs to go into the naming.
=> Upgrades `with()` method to propagate `.compute`

DESCRIPTION, NEWS.md, R/daemons.R, R/launchers.R, R/mirai-package.R, man/remote_config.Rd, tests/tests.R
=> Continuity for daemons() error behaviour introduced in mirai 2.1.0

vignettes/shiny.Rmd
Documenting that `mirai_map()` may now be invoked in an ExtendedTask directly.
Addresses part of #220.
=> Add `mirai_map()` ExtendedTask example to Shiny vignette

DESCRIPTION, NEWS.md, R/mirai.R, tests/tests.R
See #240. Closes shikokuchuo/nanonext#97.
=> Fix for stop_mirai() interrupts

DESCRIPTION, NEWS.md, R/mirai.R, man/mirai.Rd
Closes #251.
Uses a new interface in nanonext.
=> Support async mirai cancellation upon timeout

DESCRIPTION, NEWS.md, R/mirai.R
Courtesy of https://github.com/r-lib/nanonext/pull/111. We now have a reference to the original send context, so we can also use that for sending the cancellation request. We consequently no longer have to append the compute profile name as an attribute, so this makes mirai creation faster as well.
=> Efficiency / Performance Improvements in mirai Creation and Cancellation

DESCRIPTION, NEWS.md, R/mirai.R, R/next.R
Fixes errors introduced in #255. Notably `request()` argument `msgid` must be NULL if there is no relevant msgid, requiring a patch to the internal `next_msgid()`.
Additionally simplifies ephemeral mirai creation.
=> Efficiency / Performance Improvements in mirai Creation and Cancellation (follow up)

DESCRIPTION, NEWS.md, R/daemon.R, R/dispatcher.R
To align with UI consistency updates at nanonext.
=> Eliminate use of 'error' argument for listen/dial

NEWS.md, R/daemons.R, R/map.R, R/mirai-package.R, man/mirai_map.Rd, tests/tests.R
Closes #310.
Scope limited to local daemons creation of the type `daemons(6)`.
Offers an escape hatch of the form:
```r
daemons(url = local_url())
launch_local(6)
```
Example:
``` r
library(mirai)
daemons(2)
#> [1] 2
mirai_map(1:2, function(x) mirai::daemons(2))[]
#> [[1]]
#> 'miraiError' chr Error in mirai::daemons(2): cannot create local daemons from within a mirai map
#> [[2]]
#> 'miraiError' chr Error in mirai::daemons(2): cannot create local daemons from within a mirai map
daemons(0)
#> [1] 0
```
<sup>Created on 2025-06-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
FYI @hadley @DavisVaughan
=> Prevent local daemon creation in a mirai map

NEWS.md, R/daemons.R
Fixes #282 and #243.
Technical note: Now all daemons use the more robust path for signalling mirai (which checks for completion under mutex lock, rather than by using `nng_aio_busy()`)
=> Fixes `unresolvedValue` appears in fulfilled promises (non-dispatcher daemons)

DESCRIPTION, NEWS.md, R/daemons.R
By instead requiring nanonext >= 1.6.1.9001. i.e. this will automatically be resolved when the next version of nanonext is released.
Fixes #243, #317 more broadly and closer to source.
=> Reverts #317 and solves differently

NEWS.md, R/daemon.R, R/daemons.R, R/dispatcher.R, man/dispatcher.Rd
Closes #337.
- #336 already eliminates argument `rs`
- Removes arguments `tls` and `pass`
- Removes argument `signal`, calling `tools::SIGTERM` directly on dispatcher
=> Simplifies `dispatcher()` function signature

DESCRIPTION, R/daemons.R, tests/tests.R
=> Ensure reproducible RNG stream equivalence across dispatcher and non-dispatcher cases

DESCRIPTION, R/daemons.R, R/launchers.R, R/next.R, tests/tests.R
Follow up to #339. Ensures subsequent `launch_local()` and `launch_remote()` calls don't affect the stream when using a reproducible seed at `daemons()`, i.e. ensure that only `mirai()` advances the stream in this case.
=> Make reproducible seeds independent of daemon launches

NEWS.md, R/mirai.R, man/everywhere.Rd, tests/tests.R
Fixes #354 by automatically appending an empty `mirai()` evaluation at the end of the `everywhere()` call. This is invisible to the user, but ensures that the synchronization points at dispatcher are always exited.
=> Make safe consecutive `everywhere()` calls

DESCRIPTION, NEWS.md
Closes #378.
We now error if the serialization hook function errors, or otherwise fails to return the required raw vector.
=> Require nanonext with updated `serial_config()` behaviour

NEWS.md, R/daemon.R, R/daemons.R, R/mirai-package.R, man/daemon.Rd, man/daemons.Rd, tests/tests.R
Closes #383.
Revert mirai to the behaviour prior to 2.1.0.
=> Make `daemons()` calls reset any existing daemons

R/daemon.R, R/mirai.R
Avoid possible collisions with user-supplied arguments.
=> Safer naming of internal mirai elements

NEWS.md, R/daemons.R, man/daemons.Rd, tests/tests.R
Ensuring stability of return types, as follow up to #412.
=> `daemons()` with no arguments no longer returns `status()`

R/daemons.R, dev/vignettes/_mirai.Rmd, vignettes/.gitignore, vignettes/mirai.Rmd
Following up on https://github.com/r-lib/mirai/discussions/455, this adds a short sentence to give users guidances on setting `daemons`.
=> Add note about cores to documentation

R/dispatcher.R
This is the logical counterpart to taking out the `outq[[id]][["msgid"]] < 0` check at dispatcher in #461.
We should not be trying to maintain any state ourselves where interrupts are involved as these are inherently racy and unsynchronizable.
=> Minimize state at dispatcher - follow up to #461
