r-lib/mirai

DESCRIPTION
NEWS.md
R/daemon.R
R/mirai.R

daemon() records initial state of global environment

---

R/promises.R

wraps promise with:  `promises::then(onRejected = unlist)`

Handle onRejected for promises

---

R/promises.R

Brings across this PR: https://github.com/jcheng5/mirai/pull/1 after merging #103.

Preserve deep stacks when a mirai error occurs in a Shiny app

---

DESCRIPTION
NEWS.md
R/daemons.R

Addresses the slowness pointed out in #123.

Launch local daemons asynchronously

---

DESCRIPTION
NEWS.md
R/map.R
R/promises.R
vignettes/mirai.Rmd

This should speed up the vast majority of cases with ~ thousands or tens of thousands of promises. The million promises challenge is slower though.

Pushes mirai_map() performance & makes promises logic more robust

---

DESCRIPTION
NEWS.md
R/map.R
man/dot-flat.Rd

E.g. `mirai::.flat`, `mirai::.progress` etc.

Compile to bytecode mirai_map() params

---

NEWS.md
R/map.R
README.Rmd
README.md
man/mirai_map.Rd
tests/tests.R
vignettes/mirai.Rmd
vignettes/mirai.Rmd.orig

Limit 2D map to matrices and dataframes

---

vignettes/mirai.Rmd
vignettes/mirai.Rmd.orig

Adds using mirai in a package section to vignette

---

DESCRIPTION

@jcheng5 as we discussed.
There's always been a mention of you in the readme: https://shikokuchuo.net/mirai/#thanks but this makes it more 'official'.
Thanks again for the contributions, not just for event-driven promises but also the tight integration within Shiny.

Adds Joe as contributor

---

R/dispatcher.R
R/launchers.R
tests/tests.R

A round of optimization post-v2 release.

Optimization

---

NEWS.md
R/map.R
R/mirai.R
vignettes/mirai.Rmd

Report index number in error output of `mirai_map(...)[.stop]` or `collect_mirai(..., .stop)`.

Improve mirai_map() error reporting

---

NEWS.md
R/map.R

Updated for all options including `.flat`. Completes #186.

Further enhancements for mirai_map()

---

DESCRIPTION
NEWS.md
R/map.R
tests/tests.R

Preserve classes in `mirai_map()` multiple map

---

DESCRIPTION
NEWS.md
R/map.R
vignettes/mirai.Rmd
vignettes/mirai.Rmd.orig

Align with practice in {purrr}.

Improve `mirai_map()` error reporting

---

R/daemon.R
R/mirai.R

Fixes #216.
Includes misc. improvements.

Stability of `miraiError` Stack Traces

---

NEWS.md
R/mirai.R

Fixes #218.
Thanks to @lionel- for the discussion on Slack.

Strip srcref on a 'miraiError' $call

---

R/daemons.R
R/launchers.R
R/map.R
R/mirai.R

Fixes indirection for daemons `with()` method

---

vignettes/mirai.Rmd
vignettes/mirai.Rmd.orig

Add `box::use()` example to mirai vignette

---

R/daemons.R
man/daemons.Rd

Fix: prevent daemons creation if remote launch failed

---

.Rbuildignore
.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/pr-commands.yaml
.github/workflows/test-coverage.yaml
.gitignore
DESCRIPTION
R/daemon.R
R/daemons.R
R/dispatcher.R
R/launchers.R
R/map.R
R/mirai-package.R
R/mirai.R
R/next.R
R/parallel.R
R/promises.R
README.Rmd
README.md
codecov.yml
man/mirai-package.Rd

Upkeep 2025 04

---

DESCRIPTION
NEWS.md
R/mirai.R
man/mirai-package.Rd

Efficiency / Performance Improvements in mirai Creation and Cancellation (follow up)

---

.Rbuildignore
DESCRIPTION
NEWS.md
cran-comments.md

mirai 2.3.0

---

README.Rmd
README.md

For @traversc for his innovative ideas on serialization that were implemented in mirai 2.3.0.

Add Thanks and Attribution in Readme

---

DESCRIPTION
NEWS.md
R/daemons.R

Fixes the issue reported in https://github.com/eitsupi/neo-r-polars/issues/370 that was introduced by https://github.com/r-lib/mirai/pull/292.

Fix applying custom serialization to socket

---

DESCRIPTION
NEWS.md
cran-comments.md

mirai 2.4.0

---

NEWS.md
dev/vignettes/_mirai.Rmd
vignettes/mirai.Rmd

Add use of HPC job arrays to vignette

---

R/daemon.R

Eliminate warnings from NULL .Random.seed

---

R/daemons.R
R/dispatcher.R
R/launchers.R

Eliminate 'output' extraction from `...` args

---

NEWS.md
R/daemons.R
R/map.R
man/require_daemons.Rd
tests/tests.R

Make `require_daemons()` update non-breaking

---

README.Rmd
README.md

Closes #368.
- Improved intro section
- Code consolidated under a single block that can be copied and run
- Updated design concepts
- Key features section
- Simplify and bring installation upfront

Modernize readme

---

NEWS.md
R/promises.R

Closes #377. Make robust for extreme high throughput cases.

Simplify promises method

---

NEWS.md
R/mirai.R

fix(error): append newline at the end

---

dev/vignettes/_mirai.Rmd
dev/vignettes/_v06-questions.Rmd
vignettes/mirai.Rmd
vignettes/v06-questions.Rmd

Update vignettes for error behaviour and random number generation

---

R/daemons.R
dev/vignettes/_mirai.Rmd
man/daemons.Rd
man/with_daemons.Rd
vignettes/mirai.Rmd

Covers:
- `with_daemons()` and `local_daemons()`
- Re-organize other sections of reference vignette

Update vignettes with latest changes

---

R/daemon.R

A better solution to https://github.com/r-lib/mirai/pull/388 in completing #350.

Restore sink on normal exit from `daemon()`

---

README.Rmd
README.md

Merge: Key Features + Design Concept -> Design Philosophy
Update: Powers R Ecosystem & Acknowledgements sections

Refresh readme for release

---

README.Rmd
README.md

✨ Readme ✨

---

DESCRIPTION
NEWS.md
cran-comments.md

mirai 2.5.0

---

DESCRIPTION
NEWS.md
cran-comments.md

mirai 2.5.1
